# Generated by Django 2.2.6 on 2019-10-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Subject No.')),
                ('name', models.CharField(max_length=20, verbose_name='Subject Name')),
                ('intro', models.CharField(default='', max_length=511, verbose_name='Introduction')),
                ('create_date', models.DateField(null=True, verbose_name='Create Date')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Hot Subject')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subject',
                'db_table': 'tb_subject',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('no', models.IntegerField(primary_key=True, serialize=False, verbose_name='Teacher No.')),
                ('name', models.CharField(max_length=20, verbose_name='Teacher Name')),
                ('detail', models.CharField(default='', max_length=1023, verbose_name='Details')),
                ('photo', models.CharField(default='', max_length=1023, verbose_name='Photo')),
                ('Subject', models.ForeignKey(db_column='sno', on_delete=django.db.models.deletion.PROTECT, to='vote.Subject', verbose_name='Teaching Subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teacher',
                'db_table': 'tb_teacher',
            },
        ),
    ]
